name: Build Beta Branch

on:
  push:
    branches:
      - beta

jobs:
  build-and-push:
    name: "Build And Push Beta Branch"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./aioegg/beta
          file: ./aioegg/beta/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/sturdystubs/aioegg:beta