name: Build Dev Branches

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - 'games/**'

jobs:
  push:
    name: "games:${{ github.event.ref_slug }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./games/${{ github.event.ref }}
          file: ./games/${{ github.event.ref }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sturdystubs/games:${{ steps.extract_branch.outputs.branch_name }}